[project]
name = "wyslij_co"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "flask-flatpages>=0.8.3",
    "frozen-flask>=1.0.2",
    "pyyaml>=6.0.2",
    "ruff>=0.14.8",
]
